#!/bin/zsh

URL=$1

function findBrowser {
    processName=$1
    ps ax | grep "$processName" | grep -v grep | wc -l
}

CNTFF=`findBrowser "firefox"`
CNTCH=`findBrowser "chromium"`

echo "$*" > $HOME/logurls

if [ $CNTFF -ge 1 ] 
then
    /usr/bin/firefox "$URL"
elif [ $CNTCH -ge 1 ] 
then
    sudo killall chromium	
    /usr/bin/chromium "$URL"
else
    echo "No running browser instance"
fi
