source ~/.antigen/antigen.zsh clone/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

autoload -U colors && colors
autoload -U promptinit && promptinit
autoload -U compinit && compinit

antigen-bundles <<EOBUNDLES

git
command-not-found
screen
rsync
extract
zsh-users/zsh-completions src
zsh-users/zsh-syntax-highlighting

EOBUNDLES

# Load the theme.
antigen-theme dvanallen/zsh_themes themes/low_key

# Tell antigen that you're done.
antigen apply

# Define aliases.
export EDITOR="vim"
alias nmount="mount /media/ninja"
alias numount="fusermount -u /media/ninja"
alias ninja='ssh dvan@ninjabox.biz'
alias dvaorg="ssh dvan@danielvanallen.org"
alias cs1="ssh djv091020@cs1.utdallas.edu"
